### ISSUE TITLE
Unturned 4.0 with Unreal Engine?

### ISSUE THREAD

**Issue by M0RG4N01** [OxideMod/Oxide.Unturned#2]
Hello, I would like to know if Oxide plans to release a mod framework for Unturned 4.0 which will be created using Unreal Engine. 

It would be cool to see the competition between Rocket and Oxide, as I already see that Rocket is currently developing a Hurtworld and Rust mod framework. 

I understand that Oxide is mainly based in Unity, however it is a wonder for me weather Oxide will do this as a competitive move towards Rocket as Rocket is currently being competitive by creating their own Mod frameworks for games that Oxide is mainly known to have a framework. 

Warm regards,
Morgan

**Comment by lukespragg** [comment]
It isn't possible for us to support the Unreal Engine at this point, not until the Oxide.Native bridge is completed and usable.
